### ISSUE TITLE
AddOn-Name

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/bootstrap#4]
Wäre hier nicht etwas wie bootstrap_helper passender?

**Comment by aeberhard** [comment]
Hey Oliver, schau doch mal hier ... es gibt auch ein documentation-plugin
https://github.com/FriendsOfREDAXO/demo_addon

**Comment by olien** [comment]
Hi Andi,

Danke. Ist schon lang drin...

Küsschen
Oliver

**Comment by olien** [comment]
Done
